name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ mian ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t amir/docker-react -f Dockerfile.dev .

      - name: Run tests inside Docker container
        run: docker run -e CI=true amir/docker-react npm run test
